### ISSUE TITLE
Fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by mhall119** [bflanagin/EduSteem#20]
I installed qtcreator from Ubuntu's archives, and also a bunch of qt*-dev packages to get it to build, but now it's failing to run with the following error: 

`QQmlApplicationEngine failed to load component
qrc:/main.qml:2 module "QtQuick.Window" version 2.11 is not installed`

Ubuntu 18.04 has Qt 5.9.5 in it's archives.

**Comment by bflanagin** [comment]
As of ubuntu 18.10 (and its derivatives) you can build edusteem via the qt found in the repositories. I'll try to keep in line with the distributed version from here on.
